version: '3'

services:
  lp:
    container_name: "lp_page"
    build:
      context: ./
      target: pwa_dev
    volumes:
      - ./:/usr/src    
    ports:
      - target: 3000
        published: 3333
        protocol: tcp
